import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import charityImage from '../public/vecteezy_activism-donation-illustration_KN1220.jpg';
export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href='https://nextjs.org'>Next.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					<a href='https://nextjs.org/docs' className={styles.card}>
						<article>
							<button className='yellow_button'>
								<h3>Fundraise</h3>
							</button>
							<div>
								<h2>Fundraise for a World Gift</h2>
								<Image
									src={charityImage}
									alt='People donating boxes of supplies while wearing masks'
								/>
								<p>
									World Gifts are ethical charity gifts that are perfect to
									fundraise for as a parish or with friends and family
								</p>
								<div className='more'>
									<h2>More;</h2>
									<ul>
										<a>
											<li> World GIfts to buy as a group</li>
										</a>
										<a>
											<li> Set up your JuatGiving page</li>
										</a>
										<a>
											<li> World Gifts A-Z of fundraising </li>{' '}
										</a>
									</ul>
								</div>
							</div>
						</article>
					</a>
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
